apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  chess-game:
    if: ${{ fromJSON(inputs.manifest)['chess-game']['index.docker.io/cbpautomation/python-hello-world-docker'].deploy }}
    uses: ksalt/chess-game/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['chess-game']['index.docker.io/cbpautomation/python-hello-world-docker'].id }}
      environment: ${{ inputs.environment }}
